import Foundation
import CryptoKit

/// Remote model catalogue.
///
/// The list of downloadable models lives at a stable URL so it can change without
/// shipping an app update. `WhisperModel.all` stays compiled in and takes over
/// whenever the manifest is unreachable or cannot be understood, so the app is
/// never worse off than before the catalogue went remote.
///
/// The manifest is generated by `scripts/generate-models-manifest.py`, which reads
/// the same Swift array and enriches it with sha256 and exact byte sizes pulled
/// from Hugging Face's LFS metadata.
enum ModelCatalog {

    static let manifestURL = URL(string: "https://hyperstack.ru/corvin/models.json")!
    static let supportedSchemaVersion = 1

    /// Where a catalogue came from — surfaced for diagnostics, not for logic.
    enum Source: String {
        case remote     // freshly fetched
        case cached     // last good fetch, replayed offline
        case bundled    // compiled-in fallback
    }

    // MARK: - Manifest DTOs

    /// Decoded straight from JSON. Kept separate from `WhisperModel` so that adding
    /// a field to the manifest never changes how the compiled-in array is built.
    struct Manifest: Decodable {
        let schemaVersion: Int
        let generatedAt: String?
        let models: [Entry]
    }

    struct Entry: Decodable {
        let id: String
        let name: String
        let size: String
        let ramRequired: String
        let quality: String
        let speed: String
        let downloadURL: URL
        let sha256: String
        let sizeBytes: Int64?
        let minAppVersion: String?
        let recommended: Bool
        let chipRequirement: String?
        let tier: String

        func asModel() -> WhisperModel {
            WhisperModel(
                id: id, name: name, size: size, ramRequired: ramRequired,
                quality: quality, speed: speed, downloadURL: downloadURL,
                sha256: sha256,
                recommended: recommended,
                chipRequirement: chipRequirement.flatMap(ChipType.init(rawValue:)),
                tier: ModelTier(rawValue: tier) ?? .free,
                sizeBytes: sizeBytes
            )
        }
    }

    // MARK: - Fetching

    /// Fetches the manifest, falling back to the on-disk cache and finally to the
    /// compiled-in array. Never throws: a catalogue is always returned.
    static func load(cacheDirectory: URL, appVersion: String) async -> (models: [WhisperModel], source: Source) {
        if let data = await fetch(), let models = decode(data, appVersion: appVersion) {
            writeCache(data, to: cacheDirectory)
            flog("ModelCatalog: loaded \(models.count) models from manifest")
            return (models, .remote)
        }
        if let data = readCache(from: cacheDirectory), let models = decode(data, appVersion: appVersion) {
            flog("ModelCatalog: manifest unreachable, using cached catalogue (\(models.count) models)")
            return (models, .cached)
        }
        flog("ModelCatalog: falling back to the compiled-in catalogue")
        return (WhisperModel.all, .bundled)
    }

    private static func fetch() async -> Data? {
        var request = URLRequest(url: manifestURL)
        request.timeoutInterval = 15
        request.cachePolicy = .reloadIgnoringLocalCacheData
        do {
            let (data, response) = try await URLSession.shared.data(for: request)
            guard let http = response as? HTTPURLResponse, http.statusCode == 200 else {
                flog("ModelCatalog: manifest HTTP \((response as? HTTPURLResponse)?.statusCode ?? -1)")
                return nil
            }
            return data
        } catch {
            flog("ModelCatalog: manifest fetch failed: \(error.localizedDescription)")
            return nil
        }
    }

    private static func decode(_ data: Data, appVersion: String) -> [WhisperModel]? {
        guard let manifest = try? JSONDecoder().decode(Manifest.self, from: data) else {
            flog("ModelCatalog: manifest did not decode")
            return nil
        }
        guard manifest.schemaVersion == supportedSchemaVersion else {
            // A newer schema means a newer app is expected to read it; refusing here
            // keeps an old client on its known-good catalogue instead of guessing.
            flog("ModelCatalog: unsupported schemaVersion \(manifest.schemaVersion)")
            return nil
        }
        let usable = manifest.models.filter { entry in
            guard let minimum = entry.minAppVersion else { return true }
            return compareVersions(appVersion, minimum) >= 0
        }
        guard !usable.isEmpty else {
            flog("ModelCatalog: manifest has no models this build can use")
            return nil
        }
        if usable.count != manifest.models.count {
            flog("ModelCatalog: \(manifest.models.count - usable.count) models need a newer app version")
        }
        return usable.map { $0.asModel() }
    }

    /// Numeric dotted-version compare. Returns -1, 0 or 1.
    static func compareVersions(_ lhs: String, _ rhs: String) -> Int {
        let a = lhs.split(separator: ".").map { Int($0) ?? 0 }
        let b = rhs.split(separator: ".").map { Int($0) ?? 0 }
        for i in 0..<max(a.count, b.count) {
            let x = i < a.count ? a[i] : 0
            let y = i < b.count ? b[i] : 0
            if x != y { return x < y ? -1 : 1 }
        }
        return 0
    }

    // MARK: - Cache

    private static func cacheFile(_ directory: URL) -> URL {
        directory.appendingPathComponent("models-manifest.json")
    }

    private static func writeCache(_ data: Data, to directory: URL) {
        try? data.write(to: cacheFile(directory), options: .atomic)
    }

    private static func readCache(from directory: URL) -> Data? {
        try? Data(contentsOf: cacheFile(directory))
    }

    // MARK: - Hashing

    /// Streams the file so a 3 GB model does not have to fit in memory.
    static func sha256(ofFileAt url: URL) -> String? {
        guard let handle = try? FileHandle(forReadingFrom: url) else { return nil }
        defer { try? handle.close() }
        var hasher = SHA256()
        while true {
            guard let chunk = try? handle.read(upToCount: 4 * 1024 * 1024), !chunk.isEmpty else { break }
            hasher.update(data: chunk)
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
}

// MARK: - Installed model bookkeeping

/// Tracks what is actually on disk, so an updated manifest entry can be told apart
/// from the copy the user already has.
struct InstalledModelRecord: Codable, Equatable {
    let sha256: String
    let sizeBytes: Int64
    let installedAt: Date
}

final class InstalledModelStore {
    private let file: URL
    private var records: [String: InstalledModelRecord]

    init(directory: URL) {
        file = directory.appendingPathComponent("installed-models.json")
        if let data = try? Data(contentsOf: file),
           let decoded = try? JSONDecoder().decode([String: InstalledModelRecord].self, from: data) {
            records = decoded
        } else {
            records = [:]
        }
    }

    func record(for id: String) -> InstalledModelRecord? { records[id] }

    func set(_ record: InstalledModelRecord, for id: String) {
        records[id] = record
        persist()
    }

    func remove(_ id: String) {
        records.removeValue(forKey: id)
        persist()
    }

    private func persist() {
        guard let data = try? JSONEncoder().encode(records) else { return }
        try? data.write(to: file, options: .atomic)
    }
}
